//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ID { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> MaxDiscountID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CurrentDiscount { get; set; }
        public Nullable<int> WarehouseAmount { get; set; }
        public string Description { get; set; }
        public string PhotoName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MaxDiscountType MaxDiscountType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
